controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    y_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    x_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

y_joint_trajectory_controller:
  ros__parameters:
    joints:
      - y_control_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

x_joint_trajectory_controller:
  ros__parameters:
    joints:
      - x_control_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity