routes:
  calibration:
    tol_mm: 30
    timeout_s: 8
    pause_s: 1.2
    points:
      - {x_mm: 0,   y_mm: 0}
      - {x_mm: -150,  y_mm: 150}
      - {x_mm: -150,  y_mm: 140}
      - {x_mm: 150,  y_mm: 140}
      - {x_mm: 150,  y_mm: 130}
      - {x_mm: -150,  y_mm: 130}
      - {x_mm: -150,  y_mm: 120}
      - {x_mm: 150,  y_mm: 120}
      - {x_mm: 150,  y_mm: 110}
      - {x_mm: -150,  y_mm: 110}
      - {x_mm: -150,  y_mm: 100}
      - {x_mm: 150,  y_mm: 100}
      - {x_mm: 150,  y_mm: 90}
      - {x_mm: -150,  y_mm: 90}
      - {x_mm: -150,  y_mm: 80}
      - {x_mm: 150,  y_mm: 80}
      - {x_mm: 150,  y_mm: 70}
      - {x_mm: -150,  y_mm: 70}
      - {x_mm: -150,  y_mm: 60}
      - {x_mm: 150,  y_mm: 60}
      - {x_mm: 150,  y_mm: 50}
      - {x_mm: -150,  y_mm: 50}
      - {x_mm: -150,  y_mm: 40}
      - {x_mm: 150,  y_mm: 40}
      - {x_mm: 150,  y_mm: 30}
      - {x_mm: -150,  y_mm: 30}
      - {x_mm: -150,  y_mm: 20}
      - {x_mm: 150,  y_mm: 20}
      - {x_mm: 150,  y_mm: 10}
      - {x_mm: -150,  y_mm: 10}
      - {x_mm: -150,  y_mm: 0}
      - {x_mm: 150,  y_mm: 0}
      - {x_mm: 150,  y_mm: -10}
      - {x_mm: -150,  y_mm: -10}
      - {x_mm: -150,  y_mm: -20}
      - {x_mm: 150,  y_mm: -20}
      - {x_mm: 150,  y_mm: -30}
      - {x_mm: -150,  y_mm: -30}
      - {x_mm: -150,  y_mm: -40}
      - {x_mm: 150,  y_mm: -40}
      - {x_mm: 150,  y_mm: -50}
      - {x_mm: -150,  y_mm: -50}
      - {x_mm: -150,  y_mm: -60}
      - {x_mm: 150,  y_mm: -60}
      - {x_mm: 150,  y_mm: -70}
      - {x_mm: -150,  y_mm: -70}
      - {x_mm: -150,  y_mm: -80}
      - {x_mm: 150,  y_mm: -80}
      - {x_mm: 150,  y_mm: -90}
      - {x_mm: -150,  y_mm: -90}
      - {x_mm: -150,  y_mm: -100}
      - {x_mm: 150,  y_mm: -100}
      - {x_mm: 150,  y_mm: -110}
      - {x_mm: -150,  y_mm: -110}
      - {x_mm: -150,  y_mm: -120}
      - {x_mm: 150,  y_mm: -120}
      - {x_mm: 150,  y_mm: -130}
      - {x_mm: -150,  y_mm: -130}
      - {x_mm: -150,  y_mm: -140}
      - {x_mm: 150,  y_mm: -140}
      - {x_mm: 150,  y_mm: -150}
      - {pause_s: 1.0}

  warming_up:
    tol_mm: 30
    timeout_s: 8
    pause_s: 1.2
    points:
      - {x_mm: 0,   y_mm: 0}
      - {x_mm: -150,  y_mm: 100}
      - {x_mm: 150,  y_mm: 100}
      - {x_mm: 150,  y_mm: 90}
      - {x_mm: -150,  y_mm: 90}
      - {x_mm: -150,  y_mm: 80}
      - {x_mm: 150,  y_mm: -80}
      - {x_mm: 150,  y_mm: -90}
      - {x_mm: -150,  y_mm: -90}
      - {x_mm: -150,  y_mm: -100}
      - {pause_s: 1.0}

  scan_E5CA:
    tol_mm: 30
    timeout_s: 8
    pause_s: 1.2
    points:
      - {x_mm: 0,   y_mm: 0}
      - {x_mm: -150,  y_mm: 150}
      - {x_mm: 150,  y_mm: 150}
      - {x_mm: 150,  y_mm: 140}
      - {x_mm: -150,  y_mm: 140}
      - {x_mm: -150,  y_mm: 130}
      - {x_mm: 150,  y_mm: 130}
      - {x_mm: 150,  y_mm: 120}
      - {x_mm: -150,  y_mm: 120}
      - {x_mm: -150,  y_mm: 110}
      - {x_mm: 150,  y_mm: 110}
      - {x_mm: 150,  y_mm: 100}
      - {x_mm: -150,  y_mm: 100}
      - {x_mm: -150,  y_mm: 90}
      - {x_mm: 150,  y_mm: 100}
      - {x_mm: 150,  y_mm: 90}
      - {x_mm: -150,  y_mm: 90}
      - {x_mm: -150,  y_mm: 80}
      - {x_mm: 150,  y_mm: 80}
      - {x_mm: 150,  y_mm: 70}
      - {x_mm: -150,  y_mm: 70}
      - {x_mm: -150,  y_mm: 60}
      - {x_mm: 150,  y_mm: 60}
      - {x_mm: 150,  y_mm: 50}
      - {x_mm: -150,  y_mm: 50}
      - {x_mm: -150,  y_mm: 40}
      - {x_mm: 150,  y_mm: 40}
      - {x_mm: 150,  y_mm: 30}
      - {x_mm: -150,  y_mm: 30}
      - {x_mm: -150,  y_mm: 20}
      - {x_mm: 150,  y_mm: 20}
      - {x_mm: 150,  y_mm: 10}
      - {x_mm: -150,  y_mm: 10}
      - {x_mm: -150,  y_mm: 0}
      - {x_mm: 150,  y_mm: 0}
      - {x_mm: 150,  y_mm: -10}
      - {x_mm: -150,  y_mm: -10}
      - {x_mm: -150,  y_mm: -20}
      - {x_mm: 150,  y_mm: -20}
      - {x_mm: 150,  y_mm: -30}
      - {x_mm: -150,  y_mm: -30}
      - {x_mm: -150,  y_mm: -40}
      - {x_mm: 150,  y_mm: -40}
      - {x_mm: 150,  y_mm: -50}
      - {x_mm: -150,  y_mm: -50}
      - {x_mm: -150,  y_mm: -60}
      - {x_mm: 150,  y_mm: -60}
      - {x_mm: 150,  y_mm: -70}
      - {x_mm: -150,  y_mm: -70}
      - {x_mm: -150,  y_mm: -80}
      - {x_mm: 150,  y_mm: -80}
      - {x_mm: 150,  y_mm: -90}
      - {x_mm: -150,  y_mm: -90}
      - {x_mm: -150,  y_mm: -100}
      - {pause_s: 1.0}


  scan_HBM4:
    tol_mm: 30
    timeout_s: 8
    pause_s: 1.2
    points:
      - {x_mm: 0,   y_mm: 0}
      - {x_mm: -150,  y_mm: 100}
      - {x_mm: 150,  y_mm: 100}
      - {x_mm: 150,  y_mm: 90}
      - {x_mm: -150,  y_mm: 90}
      - {x_mm: -150,  y_mm: 80}
      - {x_mm: 150,  y_mm: -80}
      - {x_mm: 150,  y_mm: -90}
      - {x_mm: -150,  y_mm: -90}
      - {x_mm: -150,  y_mm: -100}
      - {pause_s: 1.0}